// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMMVDF7xYXrD1HUYsqoTYWW8yJxomaYHo',
    appId: '1:809315726563:web:4fefe09e01d22127d441d6',
    messagingSenderId: '809315726563',
    projectId: 'v-connect-muet-cf44b',
    authDomain: 'v-connect-muet-cf44b.firebaseapp.com',
    storageBucket: 'v-connect-muet-cf44b.firebasestorage.app',
    measurementId: 'G-3THFY7W0ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgH8KMDnx6YQeqGyBTXitIN6qXyQwX4k',
    appId: '1:809315726563:android:a6ee741c7792b0e0d441d6',
    messagingSenderId: '809315726563',
    projectId: 'v-connect-muet-cf44b',
    storageBucket: 'v-connect-muet-cf44b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZVdjmSK1hz49adjDG9aWbQZjEyGnCf-o',
    appId: '1:809315726563:ios:0d6eec24483f3a0dd441d6',
    messagingSenderId: '809315726563',
    projectId: 'v-connect-muet-cf44b',
    storageBucket: 'v-connect-muet-cf44b.firebasestorage.app',
    iosBundleId: 'com.example.vConnectMuet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZVdjmSK1hz49adjDG9aWbQZjEyGnCf-o',
    appId: '1:809315726563:ios:0d6eec24483f3a0dd441d6',
    messagingSenderId: '809315726563',
    projectId: 'v-connect-muet-cf44b',
    storageBucket: 'v-connect-muet-cf44b.firebasestorage.app',
    iosBundleId: 'com.example.vConnectMuet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMMVDF7xYXrD1HUYsqoTYWW8yJxomaYHo',
    appId: '1:809315726563:web:ed37504d3ceb94ead441d6',
    messagingSenderId: '809315726563',
    projectId: 'v-connect-muet-cf44b',
    authDomain: 'v-connect-muet-cf44b.firebaseapp.com',
    storageBucket: 'v-connect-muet-cf44b.firebasestorage.app',
    measurementId: 'G-B2YW4KDEFP',
  );
}
